### ISSUE TITLE
Unaligned access on fileystem object

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/storage-selector#24]
https://github.com/ARMmbed/storage-selector/blob/master/options/fat_filesystem.cpp#L21

The memory allocated to store the objects is a char array which is not garanteed to be 4-byte aligned.

Which means when you use this memory to create new objects, the objects can fall on unaligned addresses. Then when you try to access the members in this object, you end up with an unaligned memory access fault.

Solution to fix this problem with to force maximum alignment of the fs_instances array. @bremoran Can you explain your solution please: https://github.com/ARMmbed/core-util/blob/master/core-util/FunctionPointerBase.h#L88-L102 @pan-

**Comment by LiyouZhou** [comment]
@marcuschangarm @bridadan

**Comment by LiyouZhou** [comment]
Looks like there are compiler features you can use:
http://arminfo.emea.arm.com/help/index.jsp?topic=/com.arm.doc.dui0375g/chr1359124981436.html
or
https://stackoverflow.com/questions/42521605/placement-new-address-alignment

**Comment by bridadan** [comment]
Thanks for raising the issue!

To clarify (more as notes for myself in the future and for people unfamiliar with the implementation), the reason we're doing this funny memory munging is because the only time to set the FileSystem mount point is at construction. Since we are trying to avoid dynamic memory allocation if possible, this poses a problem since you can't "reconstruct" the objects once they're in the static array. This wouldn't be an issue if the FileSystem API supported renaming after construction, but there may be reasons for this.

SO, it looks like Mbed OS has an alignment helper `MBED_ALIGN` that works across toolchains: https://github.com/ARMmbed/mbed-os/blob/master/platform/mbed_toolchain.h#L61

@LiyouZhou @marcuschangarm Maybe we can use this to solve the issue? I'm not all that familiar with the memory alignment issues.

**Comment by bremoran** [comment]
This issue crops up any time you want to construct an object at a specific time, when it is not allocated from the heap. This shows up primarily in pool-allocated objects, vectors of objects, late construction of objects inside other objects, and statically allocated singletons. 

As it turns out, `alignas` is a C++11 feature. MBED_ALIGN looks like it has the correct behaviour on ARMCC and GCC. I expect that means it works on IAR as well.

**Comment by LiyouZhou** [comment]
https://github.com/ARMmbed/storage-selector/pull/25

**Comment by bridadan** [comment]
Thanks so much @liyouzhou! PR is merged so I'll close this. Please reopen if the problem persists.

**Comment by bremoran** [comment]
I'm pretty certain that #25 is incorrect. 

Please have a look at the ARM ABI. It states that the maximum alignment for fundamental datatypes on AArch 32 is 8-byte. On AArch 64, it is 16-byte.

The alignment should be 8-byte. Again, this will be compiler specific, program-specific, and link-order specific. It is not knowable when a failure will occur. If the class contains NO 8-byte data types, then it may not fail (FWIW, member function pointers are probably 8-byte data types, but I can't be sure). However, it seems to me that, in the absence of C++11 features such as the `alignas` operator and the `alignof` operator, or some pretty gnarly C++ (see here: http://www.wambold.com/Martin/writings/alignof.html), the best bet is to go with the max alignment of the platform which, for ARM seems to be 2x machine width, which is *probably* `2*sizeof(uintptr_t)`. There may be a cleaner solution than that.

**Comment by marcuschangarm** [comment]
@bremoran you realize you could have submitted a PR in less time it took you to write that, right? 😄

**Comment by bremoran** [comment]
Yes, but the maintainers of this repo need to know *why* the PR is required.
